namespace VRCFT.Expressions
{
    public static class VRCFTExpressions
    {
        public const string VRCFT_OSC_PREFIX = "/avatar/parameters/";

        public static readonly string[] NormalizedEyeExpressions = new string[]
        {
            "EyesY",
            "LeftEyeY",
            "RightEyeY",
            "EyesWiden",
            "LeftEyeWiden",
            "RightEyeWiden",
            "EyesSqueeze",
            "LeftEyeSqueeze",
            "RightEyeSqueeze",
            "EyesDilation",
            "EyesPupilDiameter",
            "LeftEyeLid",
            "RightEyeLid",
            "CombinedEyeLid",
            "LeftEyeLidExpanded",
            "RightEyeLidExpanded",
            "CombinedEyeLidExpanded",
            "LeftEyeLidExpandedSqueeze",
            "RightEyeLidExpandedSqueeze",
            "CombinedEyeLidExpandedSqueeze",
            "LeftEyeLidExpanded",
            "RightEyeLidExpanded",
            "CombinedEyeLidExpanded",
            "LeftEyeLidExpandedSqueeze",
            "RightEyeLidExpandedSqueeze",
            "CombinedEyeLidExpandedSqueeze",
            "LeftEyeWidenToggle",
            "RightEyeWidenToggle",
            "EyesWidenToggle",
            "LeftEyeSqueezeToggle",
            "RightEyeSqueezeToggle",
            "EyesSqueezeToggle",
            "EyeTrackingActive",
        };

        // Possible TODO: Add combined lip shapes
        public static readonly string[] NormalizedMouthExpressions = new string[]
        {
            "JawRight",
            "JawLeft",
            "JawForward",
            "JawOpen",
            "MouthApeShape",
            "MouthUpperRight",
            "MouthUpperLeft",
            "MouthLowerRight",
            "MouthLowerLeft",
            "MouthUpperOverturn",
            "MouthLowerOverturn",
            "MouthPout",
            "MouthSmileRight ",
            "MouthSmileLeft",
            "MouthSadRight",
            "MouthSadLeft",
            "CheekPuffRight",
            "CheekPuffLeft",
            "CheekSuck",
            "MouthUpperUpRight",
            "MouthUpperUpLeft",
            "MouthLowerDownRight",
            "MouthLowerDownLeft",
            "MouthUpperInside",
            "MouthLowerInside",
            "MouthLowerOverlay",
            "TongueLongStep1",
            "TongueLongStep2",
            "TongueDown",
            "TongueUp ",
            "TongueRight ",
            "TongueLeft ",
            "TongueRoll",
            "TongueUpLeftMorph",
            "TongueUpRightMorph",
            "TongueDownLeftMorph",
            "TongueDownRight",
        };
    }
}
